### ISSUE TITLE
Critical error when plugin is enabled

### ISSUE THREAD

**Issue by margglee** [its-cloudflare/umich-cloudflare#1]
Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /code/wp-content/plugins/umich-cloudflare/integrations/pantheon/pantheon.php:299 Stack trace: #0 /code/wp-content/plugins/umich-cloudflare/integrations/pantheon/pantheon.php(89): UMCloudflare_Pantheon::_isPantheonAdvancedActive() #1 /code/wp-includes/class-wp-hook.php(324): UMCloudflare_Pantheon::{closure}(Object(WP)) #2 /code/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #3 /code/wp-includes/plugin.php(565): WP_Hook->do_action(Array) #4 /code/wp-includes/class-wp.php(830): do_action_ref_array('wp', Array) #5 /code/wp-includes/functions.php(1336): WP->main('') #6 /code/wp-blog-header.php(16): wp() #7 /code/index.php(17): require('/code/wp-blog-h...') #8 {main} thrown in /code/wp-content/plugins/umich-cloudflare/integrations/pantheon/pantheon.php on line 299
There has been a critical error on this website.

**Comment by margglee** [comment]
I'm getting this issue when I migrated ssc.umich.edu (part of the umsites.org multisite)

**Comment by margglee** [comment]
`include_once( ABSPATH . 'wp-admin/includes/plugin.php' );` on line 299 of wp-content/plugins/umich-cloudflare/integrations/pantheon/pantheon.php may solve the issue
